#port
server:
  port: 9000

#endpoints，查看spring容器信息
management:
  endpoints:
    web:
      exposure:
        include: '*'

#nacos
nacos:
  config:
    server-addr: 127.0.0.1:8848

spring:
  redis:
#    redisson:
#      config: |
#        singleServerConfig:
#          address: "redis://127.0.0.1:6379"
#          password: 123456
#        lockWatchdogTimeout: 40000
    #Redis数据库索引（默认0）
    database: 0
    #Redis服务器地址（默认localhost）
    host: 127.0.0.1
    #Redis服务器连接端口号（默认6379）
    port: 6379
    #Redis服务器连接密码（默认为空）
    password: 123456
    lettuce:
      pool:
        max-idle: 8
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
          username: root
          password: 1314
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
          username: root
          password: 1314
          driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        min-idle: 1 #最小连接数
        max-pool-size: 2 #最大连接数
        idle-timeout: 300000 #最大空闲时间
        max-lifetime: 1800000 #最大生命周期
        connection-timeout: 5000 #超时时间
        connection-test-query: SELECT 1 #心跳检测
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

#test
test:
  user:
    id: 12
    name: zengkai
property:
  test:
    id: 1324
    name: zengkai
show:
  flow:
    add-show:
      push-channel: true
      push-wencai: true
      deleteCache: true
    edit-show:
      push-channel: true
      push-wencai: true
      deleteCache: false
  flow-new:
    add-show:
      push-channel: 1
      deleteCache: 3

