spring:
  redis:
    #Redis数据库索引（默认0）
    database: 0
    #Redis服务器地址（默认localhost）
    host: 127.0.0.1
    #Redis服务器连接端口号（默认6379）
    port: 6379
    #Redis服务器连接密码（默认为空）
    password: 123456

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1314
    druid:
      # 初始化，最小，最大连接数
      initialSize: 3
      minidle: 3
      maxActive: 18
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 5000
      #3.基础监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        #设置不统计哪些URL
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 100
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        #设置监控页面的登录名和密码
        #监控访问地址:http://localhost:9000/druid
        login-username: admin
        login-password: 1234
        allow: 127.0.0.1

test:
  user:
    id: 12
    name: 'zengkai'

property:
  test:
    id: 1324
    name: zengkai